# Schema for the configuration files of the crm_core_data module.

crm_core_data.record_type.*:
  type: config_entity
  label: 'Record type'
  mapping:
    label:
      type: label
      label: 'Name'
    id:
      type: string
      label: 'Machine-readable name'
    description:
      type: text
      label: 'Description'
    locked:
      type: boolean
      label: 'Whether or not this type is locked.'
    primary_fields:
      type: sequence
      label: 'The fields the record uses primarily'
      sequence:
        type: string
        label: 'Field'
